### ISSUE TITLE
'module' object has no attribute 'connect'

### ISSUE THREAD

**Issue by thevillem** [paragbaxi/qualysapi#7]
Hello,

I am having some trouble getting qualysapi to work on xubuntu 14.04 with python 2.7.6.

Using the basic example `qualysapi.connect(remember_me_always=True)` in the python shell returns the same error.

Trying `from qualysapi import *` and `from qualysapi import connect` both don't work when trying to use .connect.

Please let me know if there is anything that I can include to help troubleshoot this issue.
